### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
In particular the limitation to `dask <2` was very restrictive for people who run scientific HPCs.

**Comment by bocklund** [comment]
The API changes from dask and distributed 1 to 2 and emcee 2 to 3 currently break ESPEI.

dask and distributed 2 are fixable, ESPEI’s ImmediateClient needs to change to update to use client.submit and client.gather instead of calling client.map.

emcee 3 changes the shape of the trace and breaks code in ESPEI and in downstream packages like pduq. To fix, I’d want to change the axes order  from emcee 3 back to emcee 2 style.

Freeing these requirements will break ESPEI if this build is merged and installed.

**Review by bocklund — CHANGES_REQUESTED** [review]
.

**Comment by jan-janssen** [comment]
In that case it maybe also makes sense to add these requirements to `setup.py` so pip users are aware of these limitations. It was confusing for me to find these limitations here in the conda config while there are no such limitations for pip.

**Pull request closed without merging**
